### ISSUE TITLE
compilation failed

### ISSUE THREAD

**Issue by ggarlic** [rnons/lord#7]
```log
Configuring lord-2.20150122...
Building lord-2.20150122...
Preprocessing library lord-2.20150122...
[1 of 8] Compiling Web.Radio.EightTracks.User ( Web/Radio/EightTracks/User.hs, dist/build/Web/Radio/EightTracks/User.o )
[2 of 8] Compiling Web.Radio.EightTracks.Explore ( Web/Radio/EightTracks/Explore.hs, dist/build/Web/Radio/EightTracks/Explore.o )
[3 of 8] Compiling Web.Radio        ( Web/Radio.hs, dist/build/Web/Radio.o )

Web/Radio.hs:17:1: Warning:
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
[4 of 8] Compiling Web.Radio.Cmd    ( Web/Radio/Cmd.hs, dist/build/Web/Radio/Cmd.o )

Web/Radio/Cmd.hs:118:5:
    Non type-variable argument
      in the constraint: Data.String.IsString [a]
    (Use FlexibleContexts to permit this)
    When checking that ‘f’ has the inferred type
      f :: forall a. Data.String.IsString [a] => [a] -> [a] -> [a]
    In an equation for ‘pprGenres’:
        pprGenres gs
          = do { putStrLn $ foldr1 f (take 4 gs);
                 pprGenres $ drop 4 gs }
          where
              f a b = a ++ concat (replicate (20 - length a) " ") ++ b
```
ghc is installed by homebrew
>>>ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.2

**Comment by rnons** [comment]
Thank you for you interest. This project has not been updated for long time, while I'm afraid the API of those radio services have all been updated.

Would you mind telling me which radio service are you particularly interested in? I might find some time in the weekend to make it work again. Thanks.

**Comment by ggarlic** [comment]
hi,
douban.fm is working fine, but not "trending" and "hot"
8tracks is working, too
cmd.fm is not working
jing.fm is dead

and i looked into the log, seems like it's caused by GHC version bump.

there's a page talking about ghc 7.10.x migration:
https://ghc.haskell.org/trac/ghc/wiki/Migration/7.10

PS:As a MPD user for many years and a haskell newbie, i appreciate your work :100:

**Comment by rnons** [comment]
I wrote lord to learn haskell. 
Maybe you can help me make a new release. I've just opened three new issues: https://github.com/rnons/lord/issues?q=is%3Aopen+is%3Aissue

**Comment by ggarlic** [comment]
my pleasure.
i'll try it  :D
